#!/bin/sh

export USER="{{ .Env.USER }}"
export HOME="/home/$USER"

. "$HOME/{{ .Env.XDGC }}/shell/rc"
chown javyre "$XDG_RUNTIME_DIR"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$XDG_CONFIG_HOME/sv/enabled"

exec chpst -u "$USER:$groups" runsvdir "$svdir"
