# ==== ENV ==== #
[tasks.env__xps15]
envs = [['XDGC', '.local/etc']]
[tasks.env__FyrePC]
envs = [['XDGC', '.local/etc']]

# ==== CFG ==== #
[tasks.cfg__common]
deps = ['env']
links = [['$XDGC/nvim', 'nvim'],
         ['$XDGC/vim', 'vim'],
         ['$XDGC/shell', 'shell'],
         ['$XDGC/root', 'root'],
         ['$XDGC/i3', 'i3'],
         ['$XDGC/compton', 'compton'],
         ['$XDGC/polybar', 'polybar'],
         ['$XDGC/X11', 'X11']]

[tasks.cfg__xps15]
deps = ['cfg__common']

[tasks.cfg__FyrePC]
deps = ['cfg__common']

# ==== DFT ==== #
[tasks.default]
deps = ['cfg']
