# ==== ENV ==== #
[tasks.env__xps15]
envs = [['XDGC', '.config']]
[tasks.env__FyrePC]
envs = [['XDGC', '.local/etc']]

# ==== CFG ==== #
[tasks.cfg__common]
deps = ['env']
links = [['$XDGC/nvim', 'nvim'],
         ['$XDGC/vim', 'vim']]

[tasks.cfg__xps15]
deps = ['cfg__common']

[tasks.cfg__FyrePC]
deps = ['cfg__common']
links = [['$XDGC/root', 'root']]

# ==== DFT ==== #
[tasks.default]
deps = ['cfg']
