# ==== ENV ==== #
[tasks.env__xps15]
envs = [['XDGC', '.local/etc']]
[tasks.env__FyrePC]
envs = [['XDGC', '.local/etc']]

# ==== CFG ==== #
[tasks.cfg__common]
deps = ['env']
links = [
    ['$XDGC/alacritty.yml' , 'alacritty.yml' ],
    ['$XDGC/nvim'          , 'nvim'          ],
    ['$XDGC/vim'           , 'vim'           ],
    ['$XDGC/tmux'          , 'tmux'          ],
    ['$XDGC/shell'         , 'shell'         ],
    ['$XDGC/root'          , 'root'          ],
    ['$XDGC/i3'            , 'i3'            ],
    ['$XDGC/picom'         , 'picom'         ],
    ['$XDGC/polybar'       , 'polybar'       ],
    ['$XDGC/rofi'          , 'rofi'          ],
    ['$XDGC/X11'           , 'X11'           ],
    ['$XDGC/git'           , 'git'           ],
    ['.local/bin/s'        , 's'             ],
]

[tasks.cfg__xps15]
deps = ['cfg__common']

[tasks.cfg__FyrePC]
deps = ['cfg__common']

# ==== DFT ==== #
[tasks.default]
deps = ['cfg']
