#!/bin/sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
    layout bsp \
    focus_follows_mouse autoraise \
    window_gap     07 \
    top_padding    07 \
    bottom_padding 07 \
    left_padding   07 \
    right_padding  07 \
    window_animation_duration 0.0


# Unmanaged windows
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add title='Calculator$' manage=off
yabai -m rule --add app='Raycast' manage=off
